### ISSUE TITLE
darkmode

### ISSUE THREAD

**Issue by kyjkyj080115** [Jeongheegenius/jeongheegenius.github.io#2]
아이폰 darkmode로 켜서 자동으로 바뀔때 네비게이션 바에 있는 다크모드 전환 버튼 안바뀝니다

**Comment by Jeongheegenius** [comment]
사진도 같이 올려주세요.

**Comment by kyjkyj080115** [comment]
![Uploading 120922483...]

**Comment by kyjkyj080115** [comment]
https://user-images.githubusercontent.com/71873121/120922495-64cec080-c704-11eb-921c-3b24be53244a.MOV
