### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by kyjkyj080115** [Jeongheegenius/jeongheegenius.github.io#3]
천제가 아니라 천재입니다

**Comment by Jeongheegenius** [comment]
![이미지](https://i.esdrop.com/d/926oupxkzqeo/bEfmHnas5M.jpg)
?

**Comment by kyjkyj080115** [comment]
Just find the exact one. Just looking for something weird.

**Comment by kyjkyj080115** [comment]
![image](https://user-images.githubusercontent.com/71873121/120922533-bb3bff00-c704-11eb-89f2-c3332294e789.png)

**Comment by kyjkyj080115** [comment]
![image](https://user-images.githubusercontent.com/71873121/120922548-c98a1b00-c704-11eb-8ba1-7515489d27da.png)

**Comment by Jeongheegenius** [comment]
ah..... ok.....
