### ISSUE TITLE
이미지 화질

### ISSUE THREAD

**Issue by kyjkyj080115** [Jeongheegenius/jeongheegenius.github.io#4]
![image](https://user-images.githubusercontent.com/71873121/120889215-fff96480-c636-11eb-8acf-e69d9d188962.png)
이미지 화질좀 올려주세요

**Comment by Jeongheegenius** [comment]
원래부터 화질 저랬으니 이건 바꿀 수 없음

**Comment by kyjkyj080115** [comment]
원래라는 말은 없습니다 저거 찍은 사진기가 똥이라는 말입니까?

**Comment by kyjkyj080115** [comment]
생각좀 하고 대처하시죠

**Comment by kyjkyj080115** [comment]
이거도 열으세요
