### ISSUE TITLE
change color

### ISSUE THREAD

**Issue by kyjkyj080115** [Jeongheegenius/jeongheegenius.github.io#5]
![image](https://user-images.githubusercontent.com/71873121/120889244-1acbd900-c637-11eb-9f77-b09fd03ce754.png)
다크모드 켰을때 햄버거 바 색깔 흰색으로 바꿔주세요

**Comment by kyjkyj080115** [comment]
버튼으로 다크모드를 킬 시 색깔이 변하지만, 아이폰 다크모드로 바꾸면 햄버거 바 색깔이 안바뀝니다

**Comment by Jeongheegenius** [comment]
네 정상

**Comment by kyjkyj080115** [comment]
구현을 못하는거지 정상이라고 닫는겁니까?

**Comment by kyjkyj080115** [comment]
제대로 된 대처를 하세요

**Comment by kyjkyj080115** [comment]
구현 하려고 노력해야지 님이 아이폰 있습니까?

**Comment by kyjkyj080115** [comment]
다시 열으세요

**Comment by kyjkyj080115** [comment]
Don't dig a virtual machine with a Azure. Try your best. If it is not decided, then it will be done again
